import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="navbar">
          <Link href={"/"} className="navbtn">
            Home
          </Link>
          <Link href={"/write"} className="navbtn">
            write
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
